- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Installing npm
      ansible.builtin.shell:
        cmd: sudo apt install npm -y

    - name: Installing pm2
      ansible.builtin.shell:
        cmd: sudo npm install pm2 -g

    - name: Cloning to Fronted  Repository
      git:
        repo: 'https://github.com/ManikantaKodimala/employeePorrtalUI'
        dest: /home/ubuntu/astro-ui
        clone: yes
        update: yes
        force: yes

    - name: Building Front end
      ansible.builtin.shell:
        chdir: /home/ubuntu/astro-ui/
        cmd: npm install
#    - name: coping received data as args i.e., target
    - copy:
        dest: /home/ubuntu/target.txt
        content: "{{ target }}"

    - name: Runing frontend
      ansible.builtin.shell:
        chdir: /home/ubuntu/astro-ui/
        cmd: REACT_APP_BACKEND_IP={{ target }} pm2 start npm -- start