# This is a basic workflow to help you get started with Actions

name: Terraform Apply

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Decrypt Pem
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      run: |
            mkdir $HOME/secrets
            gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output $HOME/secrets/my_private_key.pem my-ec2-ssh.gpg
            chmod 400 $HOME/secrets/my_private_key.pem
    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_public_key: ${{secrets.TF_VAR_PUBLIC_KEY}}
        TF_VAR_private_key: ${{secrets.TF_VAR_PRIVATE_KEY}}
      run: |
            cd terraform
            terraform init

    - name: Terraform validation
      run: |
            cd terraform
            terraform validate

    - name: Terraform Plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_public_key : ${{secrets.TF_VAR_PUBLIC_KEY}}
        TF_VAR_private_key : ${{secrets.TF_VAR_PRIVATE_KEY}}
      run: |
            cd terraform
            terraform plan

    - name: Terraform Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_public_key: ${{secrets.TF_VAR_PUBLIC_KEY}}
        TF_VAR_private_key: ${{secrets.TF_VAR_PRIVATE_KEY}}
      run: |
            cd terraform
            terraform apply -auto-approve -input=false
            terraform output -json
            export IP_ADDRESS=$(terraform output -raw target)
            echo "REACT_APP_BACKEND_IP="$IP_ADDRESS > ../../.env
            cat ../../.env
            cd ../ansible
            ansible-playbook -i inventory.yaml script.yaml --private-key $HOME/secrets/my_private_key.pem --extra-vars "target=$IP_ADDRESS "